#1 サインアップ機能実装
shinonome-inc/backend-final-assignment-sasamaru pull request #1
Opened 2023-03-25 03:58 UTC by sasamaru-38

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] Django Adminに，今まで作成したモデルを全て登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-03-25 09:05 UTC, yodapuuu reviewed
よくかけてると思います！

2023-03-25 09:05 UTC, yodapuuu commented on accounts/tests.py
https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=842149650

ほかのテストの記述もお願いします！

2023-03-27 13:29 UTC, sasamaru-38 commented
修正しました！

2023-03-27 16:53 UTC, yodapuuu reviewed
めちゃいい感じです！いくつかコメントしました！

今後レビュー依頼を出すことが増えてくると思います。そこでお願いなのですが、slackでのお知らせと同様にコメントにリアクションしてくださると大変助かります！よろしくお願いします！！

2023-03-27 16:53 UTC, yodapuuu commented on accounts/tests.py
> +        self.assertFalse(User.objects.filter(username=empty_user_data["username"]).exists())
DBにレコードが追加されていないことのテストをしてくれていると思うのですが、ほかのところではself.assertEqual(User.objects.all().count(), 0)を使っていたりするのでself.assertFalse(User.objects.filter(なんか).exists())かどちらかで統一しましょう。

2023-03-27 16:53 UTC, yodapuuu commented on accounts/tests.py
> +            "password1": "",
status_codeが200であるかの記述追記お願いします。

2023-03-27 16:53 UTC, yodapuuu commented on accounts/tests.py
> +        )
ここのコードはなくても大丈夫です。

2023-03-27 16:53 UTC, yodapuuu commented on accounts/tests.py
> +        print(response)
ここも削除でお願いします。printを使って中身確認できてるのいいと思います！

2023-03-29 06:43 UTC, sasamaru-38 commented on accounts/tests.py
> +            "password1": "",
追記しました！

2023-03-29 06:43 UTC, sasamaru-38 commented on accounts/tests.py
> +        )
削除しました！

2023-03-29 07:02 UTC, sasamaru-38 commented
修正後にテスト実行したらその部分がエラーになってしまいます、、
バイトあるので今日の夜遅くになってしまいますがもう一度コードを見てみて分からないところを質問させて頂きます。
急ぎではないのですが、後日回答もらえると助かります！

2023-03-30 02:44 UTC, yodapuuu commented on accounts/tests.py
> +        print(response)
ごめんなさい指定箇所が複数行になっていますが、print(response)の部分だけ削除してくれれば大丈夫です。

2023-03-30 05:14 UTC, sasamaru-38 commented on accounts/tests.py
> +        print(response)
修正しました！

2023-03-30 05:36 UTC, sasamaru-38 commented
修正しました。self.assertEqual(User.objects.all().count(), 0)とself.assertFalse(User.objects.filter(なんか).exists())の意味について質問しようとしていたのですが調べたら分かったので大丈夫です。
確認宜しくお願いします！

2023-03-30 13:56 UTC, yodapuuu commented
LGTM

2023-03-31 01:21 UTC, Akinori13 requested changes
1点だけコメントしました！

2023-03-31 01:21 UTC, Akinori13 commented on accounts/admin.py
> +# from django.contrib import admin
管理画面でUserを管理できるようにしましょう

2023-03-31 06:32 UTC, sasamaru-38 commented on accounts/admin.py
> +# from django.contrib import admin
修正しました！

2023-03-31 08:43 UTC, Akinori13 commented
LGTM

2023-03-31 08:43 UTC, merged