Feature/login
shinonome-inc/backend-final-assignment-sasamaru pull request #2
Opened 2023-04-26 09:24 UTC by sasamaru-38

2023-04-26 13:17 UTC, SShizawa requested changes

2023-04-26 13:17 UTC, SShizawa commented on accounts/tests.py
>  # class TestUserProfileView(TestCase):
testuserprofilrviewのtestも書いてください。
https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917

2023-04-29 10:53 UTC, sasamaru-38 commented on accounts/tests.py
>  # class TestUserProfileView(TestCase):
追加しました！

2023-04-30 14:29 UTC, Akinori13 requested changes
めっちゃよく書けています！少しコメントしました！

2023-04-30 14:29 UTC, Akinori13 commented on accounts/views.py
> +        return context
不要な気がします！

2023-04-30 14:29 UTC, Akinori13 commented on tweets/models.py
> +#     user = models.ForeignKey(settings.AUTH_USER_MODEL)
不要な気がします！

2023-04-30 14:29 UTC, Akinori13 commented on tweets/views.py
> +    # model = Tweet
不要な気がします！

2023-04-30 14:29 UTC, Akinori13 commented on tweets/views.py
> +
不要な気がします！

2023-04-30 14:29 UTC, Akinori13 commented on accounts/urls.py
> +    # path("login/", LoginView.as_view(template_name="accounts/login.html"), name="login"),で、accountsの中にhome.htmlを入れる。
不要な気がします！

2023-04-30 14:29 UTC, Akinori13 commented on accounts/tests.py
> +    def test_failure_post_with_not_exists_user(self):
ここは「存在しないusername, 有効な形式のパスワードを送信する」でお願いします！※UserAというユーザーがいない想定
```
invalid_data = {
            "username": "UserA",
            "password": "password",
        }
```

2023-05-01 01:46 UTC, sasamaru-38 commented on accounts/urls.py
> +    # path("login/", LoginView.as_view(template_name="accounts/login.html"), name="login"),で、accountsの中にhome.htmlを入れる。
削除しました！

2023-05-01 01:46 UTC, sasamaru-38 commented on tweets/views.py
> +
削除しました！

2023-05-01 01:47 UTC, sasamaru-38 commented on tweets/views.py
> +    # model = Tweet
削除しました！

2023-05-01 01:47 UTC, sasamaru-38 commented on tweets/models.py
> +#     user = models.ForeignKey(settings.AUTH_USER_MODEL)
削除しました！

2023-05-01 01:58 UTC, sasamaru-38 commented on accounts/tests.py
> +    def test_failure_post_with_not_exists_user(self):
修正しました！

2023-05-01 02:06 UTC, sasamaru-38 commented on accounts/views.py
> +        return context
削除しました！

2023-05-01 03:05 UTC, Akinori13 commented
LGTM

2023-05-01 04:22 UTC, merged